"use client";

import Link from "next/link";
import Image from "next/image";
import { useEffect, useState } from "react";

import ResearchHighlights from "@/components/home/research-highlights";
import PublicationHighlights from "@/components/home/publication-highlights";
import BlogHighlights from "@/components/home/blog-highlights";
import ProjectHighlights from "@/components/home/projects-highlights";
import ExperienceHighlights from "@/components/home/experience-highlights";
import EducationHighlights from "@/components/home/education-highlights";

export default function Home() {
	const [showStickyNav, setShowStickyNav] = useState(false);

	useEffect(() => {
		const handleScroll = () => {
			const heroSection = document.getElementById("hero");
			if (!heroSection) return;

			const rect = heroSection.getBoundingClientRect();
			setShowStickyNav(rect.bottom <= 0);
		};

		window.addEventListener("scroll", handleScroll);
		return () => window.removeEventListener("scroll", handleScroll);
	}, []);

	const scrollToSection = (id: string) => {
		const el = document.getElementById(id);
		if (el) {
			el.scrollIntoView({ behavior: "smooth", block: "start" });
		}
	};

	const scrollNews = (direction: "left" | "right") => {
		const container = document.getElementById("news-scroll");
		if (!container) return;
		container.scrollBy({
			left: direction === "left" ? -300 : 300,
			behavior: "smooth",
		});
	};

	const newsItems = [
		{
			date: "May 2025",
			text: "Invited to Chair Student Research Competition at CGO 2026",
			image: "/n1.png", // Add actual image path
		},
		{
			date: "March 2025",
			text: "Presented conference talk on LLM-Vectorizer at CGO 2025",
			image: "/n1.png",
		},
		{
			date: "Feb 2025",
			text: "Gave invited LSD seminar at UCSC",
			link: "https://lsd.ucsc.edu/lsd-seminar/2025wi/",
			image: "/n1.png",
		},
	];

	return (
		<main className='min-h-screen scroll-smooth'>
			{/* Hero Section */}
<section
  id='hero'
  className='py-20 px-4 md:px-6 lg:px-8 bg-gradient-to-b from-gray-50 to-white'>
  <div className='container mx-auto max-w-6xl'>
    <div className='flex flex-col md:flex-row items-start gap-8 md:gap-12'>
      <div className='flex-1 order-2 md:order-1'>
        <h1 className='text-4xl md:text-5xl lg:text-6xl font-bold text-gray-900 mb-4'>
          Jubi Taneja
        </h1>
        <h2 className='text-xl md:text-2xl font-medium text-gray-700 mb-6'>
          PhD in Computer Science
        </h2>
        <p className='text-lg text-gray-600 mb-8 max-w-2xl whitespace-pre-line'>
          
        </p>
        <div className='flex flex-wrap gap-4'>
          <Link
            href='/contact'
            className='px-6 py-3 bg-gray-900 text-white rounded-md hover:bg-gray-800 transition-colors'>
            Contact Me
          </Link>
        </div>
      </div>

      <div className='flex-1 order-1 md:order-2 flex items-start justify-center'>
        <div className='relative w-64 h-64 md:w-80 md:h-80 rounded-full overflow-hidden border-4 border-white shadow-xl'>
          <Image
            src='/juhitaneja.jpeg'
            alt='Dr. Juhi Taneja'
            fill
            className='object-cover'
            priority
          />
        </div>
      </div>
    </div>
	<div className="pt-16">
		Jubi Taneja is a Research Engineer at Microsoft Research whose work lies at the intersection of AI, Compiler Optimizations, and Formal Verification. Her research focuses on building trustworthy compiler optimizations and leveraging LLMs to advance code generation technologies, all while ensuring correctness through formal methods.
At Microsoft Research, Jubi leads efforts to make AI-assisted code generation reliable and verifiable. She built a PTX-level kernel equivalence checker based on symbolic execution to formally verify that optimized GPU kernels—generated by large language models or handwritten—preserve the semantics of their original unoptimized implementations. She also created LLM-Vectorizer, a framework that prompts large language models to produce vectorized loops and formally verifies the transformation using Alive2 (SMT solver-based tool), presented at CGO 2025. Additionally, she contributed to Accera, a compiler for accelerating AI models on heterogeneous hardware, targeting CPUs and GPUs.

Jubi earned her Ph.D. in Computer Science from the University of Utah, where she applied formal semantics and solver-based techniques to improve compiler reliability and optimization effectiveness. She was advised by Prof. John Regehr. She contributed to Souper, a program synthesis-based superoptimizer for LLVM IR and advanced techniques for verifying the soundness and precision of LLVM’s static analyses, earning her the Distinguished Paper and Best Student Presentation Awards at CGO 2020.

Her interest in compiler research began during her undergraduate studies, when she interned at IIT Bombay, contributing to incremental compiler construction and specification-based code generation techniques. She later joined IIT Bombay as a Junior Research Fellow, where she extended dataflow analysis techniques in GCC. Dr. Taneja earned her Bachelor of Technology in Computer Science from the University College of Engineering, Punjabi University, where she received the University Gold Medal.

Beyond her technical contributions, Jubi is actively engaged in the programming languages and systems research community. She serves as a mentor in SIGPLAN-M, co-leads initiatives such as Women in Research and Moms in Research at Microsoft Research, and co-hosts the Women in Compilers and Tools Meetup Series. She has served on numerous program committees, including PLDI, CGO, and LCTES, and continues to champion mentorship and diversity within the research community.

Jubi envisions a future where compiler development evolves beyond manual engineering and hand-crafted optimizations to meet the demands of an increasingly diverse ecosystem of AI accelerators. As hardware innovation accelerates, traditional compiler design methodologies struggle to keep pace with new backends and rapidly changing workloads. She believes the next generation of compilers will be self-learning systems, where large language models and program synthesis techniques collaborate in feedback loops—LLMs proposing optimizations, while formal verification and reinforcement learning provide correctness and performance feedback, enabling the models to self-reason and self-improve. Her research aims to pioneer this paradigm shift by exploring neuro-symbolic compiler construction, where machine learning accelerates discovery and adaptation, while rigorous formal verification ensures reliability. This long-term vision seeks to democratize high-performance compilation, making it scalable, trustworthy, and responsive to the needs of emerging AI-driven computing platforms.

	</div>
  </div>
</section>


			{/* Research Interests Section */}
			<section className='bg-white py-16 px-4 md:px-6 lg:px-8 border-t border-gray-100'>
				<div className='container mx-auto max-w-6xl'>
					<h2 className='text-2xl font-semibold text-gray-900 mb-6 flex items-center gap-2'>
						<span className='text-black'>🧪 Research Interests</span>
					</h2>
					<div className='flex flex-wrap gap-4'>
						{[
							"AI for Compilers",
							"Compilers",
							"Compiler optimizations",
							"Formal Methods",
							"Superoptimization",
						].map((interest) => (
							<span
								key={interest}
								className='px-4 py-2 bg-gray-100 text-gray-800 text-sm font-medium rounded-md shadow-sm'>
								{interest}
							</span>
						))}
					</div>
				</div>
			</section>

			{/* News Section */}
			<section className='bg-gray-50 py-8 px-4 md:px-6 lg:px-8 border-t border-gray-100'>
				<div className='container mx-auto max-w-6xl'>
					<h2 className='text-2xl font-semibold text-gray-900 mb-6'>News</h2>

					<div className='space-y-4'>
					{newsItems.map((item, index) => (
						<div
						key={index}
						className='bg-white rounded-lg shadow-md border border-gray-200 p-4'
						>
						<p className='text-sm text-gray-500 mb-1 font-semibold'>
							{item.date}
						</p>
						<p className='text-gray-800 text-sm'>{item.text}</p>
						{item.link && (
							<a
							href={item.link}
							target='_blank'
							rel='noopener noreferrer'
							className='block mt-2 text-blue-600 text-sm underline'
							>
							See More
							</a>
						)}
						</div>
					))}
					</div>
				</div>
				<div className="ontainer mx-auto max-w-6xl pt-4 text-blue-600">
					See More News...
				</div>
			</section>


			{/* {/* Sticky Nav (appears after scrolling) */}
			{/* {showStickyNav && (
				<section className='fixed top-6 left-1/2 -translate-x-1/2 z-50 w-[90vw] max-w-4xl'>
					<div className='backdrop-blur-md bg-white/80 shadow-lg rounded-full px-4 py-2 border border-gray-200 transition-all duration-300'>
						<nav className='flex justify-center items-center flex-wrap gap-3'>
							{[
								"projects",
								"research",
								"blogs",
								"publications",
								"education",
								"experience",
							].map((section) => (
								<button
									key={section}
									onClick={() => scrollToSection(section)}
									className='px-4 py-1.5 text-sm font-medium text-gray-700 hover:bg-gray-100 hover:text-black transition-all duration-200 rounded-full'>
									{section.charAt(0).toUpperCase() + section.slice(1)}
								</button>
							))}
						</nav>
					</div>
				</section>
			)} */}

			{/* Placeholder Sections */}
			{/* <section
				id='projects'
				className='min-h-[80vh] px-6'>
				<ProjectHighlights></ProjectHighlights>
			</section> */}
			{/* <section
				id='research'
				className='min-h-[80vh] px-6 pt-20'>
				<ResearchHighlights></ResearchHighlights>
			</section> */}
			{/* <section
				id='blogs'
				className='min-h-[80vh] px-6 pt-20'>
				<BlogHighlights></BlogHighlights>
			</section> */}
			{/* <section
				id='publications'
				className='min-h-[80vh] px-6 pt-20'>
				<PublicationHighlights></PublicationHighlights>
			</section> */}
			{/* <section
				id='education'
				className='min-h-[50vh] px-6 pt-20'>
				<EducationHighlights></EducationHighlights>
			</section> */}
			{/* <section
				id='experience'
				className='min-h-[80vh] px-6 pt-32 pb-40'>
				<ExperienceHighlights></ExperienceHighlights>
			</section>  */}
			<section className='py-16 bg-white text-center'>
				<h2 className='text-2xl font-semibold text-gray-900 mb-4'>
					Get in Touch
				</h2>
				<p className='text-gray-600 text-sm mb-1'>
					Interested in collaborations, speaking engagements, or research
					inquiries?
				</p>
				<p className='text-gray-600 text-sm mb-6'>Feel free to reach out.</p>

				<Link
					href='/contact'
					className='inline-block px-6 py-2 bg-blue-600 text-white text-sm font-medium rounded-full shadow hover:bg-blue-700 transition'>
					Contact Me
				</Link>
			</section>
		</main>
	);
}
